import 'package:flutter_test/flutter_test.dart';
import 'package:ilink/platform/observability/observability.dart';

/// Architectural test: the IP-protective scrubber must redact every
/// pattern the mini-apps encrypted-table work hides from classes.dex.
/// A regression here (e.g. a future PR loosens the regex) would let a
/// Sentry crash report ship the family/op names + shell-command shapes
/// to a third party — defeating Phase 0–4.
void main() {
  group('Observability.debugScrub', () {
    const marker = '[REDACTED:miniapp]';

    test('redacts 16-hex op tokens', () {
      // Tokens generated by tool/generate_op_tokens.dart.
      const samples = [
        'dea75bdb7740be54',
        '32d1fb949b60ac5c',
        '9f1caa65a5487473',
        'ababd346995ec412',
      ];
      for (final s in samples) {
        expect(
          Observability.debugScrub('saw token $s in dispatch'),
          marker,
          reason: 'token $s leaked through scrubber',
        );
      }
    });

    test('redacts shell command shapes', () {
      const samples = [
        'am start-activity --activity-multiple-task --display 5 -n com.foo/.Bar',
        'am stack list',
        'am stack move-task 42 7 true',
        'am force-stop com.example.amapservice',
        'input -d 5 tap 100 200',
      ];
      for (final s in samples) {
        expect(Observability.debugScrub(s), marker, reason: s);
      }
    });

    test('redacts IP-bearing literals', () {
      const samples = [
        'mini_app_op:pkg.launch_on_display',
        'com.example.amapservice',
        'com.i99dev.ilink/.display.ClusterActivity',
        'XDJAScreenProjection_0',
      ];
      for (final s in samples) {
        expect(Observability.debugScrub(s), marker, reason: s);
      }
    });

    test('redacts plaintext family.op names', () {
      const samples = [
        'pkg.launch_on_display',
        'pkg.stack_list',
        'pkg.stack_move_task',
        'surface.am_start_cluster',
        'surface.amap_force_stop',
        'gesture.input_tap',
        'gesture.input_swipe',
        'display.cluster_name_marker',
        'display.amap_slot_marker',
      ];
      for (final s in samples) {
        expect(Observability.debugScrub(s), marker, reason: s);
      }
    });

    test('does not redact car-model / DiLink tag values', () {
      // Vehicle-context tags must pass through cleanly. A regression
      // here would mean the issue card loses its car.model / dilink.*
      // chips — exactly the triage axis we just added.
      const tagValues = [
        'Leopard 8',
        'Han',
        'Tang',
        '155',
        'fcbsq',
        'Di5.1_5.0UI',
        'DiLink5.1',
        'ae',
        'sa',
        'cn',
      ];
      for (final v in tagValues) {
        expect(
          Observability.debugScrub(v),
          isNot(equals(marker)),
          reason: 'vehicle tag value $v wrongly redacted',
        );
      }
    });

    test('passes through benign strings', () {
      const samples = [
        'WebView crashed at line 42',
        'NetworkOnMainThreadException',
        'PlatformException(MissingPluginException)',
        'displayId=5 ok=true',
        // Generic package names — not our IP, fine to log.
        'com.spotify.music launched',
        // A 16-char hex would match the token regex, so we use 17 here.
        'sha256: a1b2c3d4e5f6789012',
      ];
      for (final s in samples) {
        expect(
          Observability.debugScrub(s),
          isNot(equals(marker)),
          reason: 'false positive on benign input: $s',
        );
      }
    });
  });
}
