import '../../_car_domain/command/command.dart';

class VoiceLangPack {
  const VoiceLangPack({
    required this.commands,
    required this.numberWords,
    required this.tempTemplates,
    required this.fanTemplates,
    required this.titles,
    required this.labels,
  });

  final Map<String, List<String>> commands;
  final Map<int, String> numberWords;
  final List<String> tempTemplates;
  final List<String> fanTemplates;
  final Map<CommandCategory, String> titles;
  final Map<String, String> labels;
}

const Map<String, VoiceLangPack> voiceLangPacks = {
  // ── Russian ────────────────────────────────────────────────────────────
  'ru': VoiceLangPack(
    commands: {
      'window_down': ['опусти стекло полностью', 'открой окно до конца'],
      'window_fr_open': [
        'открой окно пассажира',
        'опусти стекло справа спереди',
      ],
      'window_fr_close': [
        'закрой окно пассажира',
        'подними стекло справа спереди',
      ],
      'window_rl_open': [
        'открой окно сзади слева',
        'опусти стекло сзади слева',
      ],
      'window_rl_close': [
        'закрой окно сзади слева',
        'подними стекло сзади слева',
      ],
      'window_rr_open': [
        'открой окно сзади справа',
        'опусти стекло сзади справа',
      ],
      'window_rr_close': [
        'закрой окно сзади справа',
        'подними стекло сзади справа',
      ],
      'defrost_off': [
        'выключи обогрев лобового стекла',
        'отключи обдув стекла',
      ],
      'defrost_rear': [
        'включи обогрев заднего стекла',
        'обогрей заднее стекло',
      ],
      'defrost_rear_off': [
        'выключи обогрев заднего стекла',
        'отключи обогрев сзади',
      ],
      'max_hot': ['максимальный обогрев', 'сделай максимальное тепло'],
      'max_cool': ['максимальное охлаждение', 'сделай максимальный холод'],
      'compressor_on': ['включи компрессор'],
      'compressor_off': ['отключи компрессор'],
      'fragrance_off': ['выключи ароматизатор', 'отключи запах'],
    },
    numberWords: {
      0: 'ноль',
      1: 'один',
      2: 'два',
      3: 'три',
      4: 'четыре',
      5: 'пять',
      6: 'шесть',
      7: 'семь',
      16: 'шестнадцать',
      17: 'семнадцать',
      18: 'восемнадцать',
      19: 'девятнадцать',
      20: 'двадцать',
      21: 'двадцать один',
      22: 'двадцать два',
      23: 'двадцать три',
      24: 'двадцать четыре',
      25: 'двадцать пять',
      26: 'двадцать шесть',
      27: 'двадцать семь',
      28: 'двадцать восемь',
      29: 'двадцать девять',
      30: 'тридцать',
      31: 'тридцать один',
      32: 'тридцать два',
    },
    tempTemplates: [
      'поставь температуру {n}',
      'установи температуру {n} градусов',
      'сделай {n} градусов',
      'температура {n}',
    ],
    fanTemplates: [
      'поставь вентилятор на {n}',
      'скорость вентилятора {n}',
      'установи обдув на {n}',
    ],
    titles: {
      CommandCategory.door: 'Двери и багажник',
      CommandCategory.window: 'Окна',
      CommandCategory.climate: 'Климат',
      CommandCategory.comfort: 'Комфорт',
      CommandCategory.status: 'Статус',
      CommandCategory.apps: 'Приложения',
    },
    labels: {
      'door.lock': 'Закрыть двери',
      'door.unlock': 'Открыть двери',
      'door.trunk.open': 'Открыть багажник',
      'window.fl.open': 'Окно водителя открыть',
      'window.fl.close': 'Окно водителя закрыть',
      'window.fl.down': 'Окно водителя вниз',
      'window.fr.open': 'Окно пассажира открыть',
      'window.fr.close': 'Окно пассажира закрыть',
      'window.rl.open': 'Окно сзади слева открыть',
      'window.rl.close': 'Окно сзади слева закрыть',
      'window.rr.open': 'Окно сзади справа открыть',
      'window.rr.close': 'Окно сзади справа закрыть',
      'climate.power': 'Климат вкл/выкл',
      'climate.defrost_f': 'Обогрев лобового стекла',
      'climate.defrost_r': 'Обогрев заднего стекла',
      'climate.max_hot': 'Максимальный обогрев',
      'climate.max_cool': 'Максимальное охлаждение',
      'climate.compressor': 'Компрессор кондиционера',
      'climate.temp': 'Температура',
      'climate.fan': 'Скорость вентилятора',
      'comfort.frag.off': 'Ароматизатор выкл',
    },
  ),

  // ── French ─────────────────────────────────────────────────────────────
  'fr': VoiceLangPack(
    commands: {
      'window_down': [
        'baisse ma vitre complètement',
        'ouvre ma vitre en entier',
      ],
      'window_fr_open': [
        'ouvre la vitre passager',
        'ouvre la vitre avant droite',
      ],
      'window_fr_close': [
        'ferme la vitre passager',
        'ferme la vitre avant droite',
      ],
      'window_rl_open': [
        'ouvre la vitre arrière gauche',
        'ouvre la vitre derrière à gauche',
      ],
      'window_rl_close': [
        'ferme la vitre arrière gauche',
        'ferme la vitre derrière à gauche',
      ],
      'window_rr_open': [
        'ouvre la vitre arrière droite',
        'ouvre la vitre derrière à droite',
      ],
      'window_rr_close': [
        'ferme la vitre arrière droite',
        'ferme la vitre derrière à droite',
      ],
      'defrost_off': ['arrête le dégivrage', 'coupe le dégivrage avant'],
      'defrost_rear': [
        'active le dégivrage arrière',
        'démarre le dégivrage arrière',
      ],
      'defrost_rear_off': [
        'arrête le dégivrage arrière',
        'coupe le dégivrage arrière',
      ],
      'max_hot': ['chauffage maximum', 'mets le chauffage au maximum'],
      'max_cool': ['climatisation maximum', 'mets la clim au maximum'],
      'compressor_on': ['allume le compresseur', 'active le compresseur'],
      'compressor_off': ['éteins le compresseur', 'coupe le compresseur'],
      'fragrance_off': ['arrête le parfum', 'coupe le diffuseur de parfum'],
    },
    numberWords: {
      0: 'zéro',
      1: 'un',
      2: 'deux',
      3: 'trois',
      4: 'quatre',
      5: 'cinq',
      6: 'six',
      7: 'sept',
      16: 'seize',
      17: 'dix-sept',
      18: 'dix-huit',
      19: 'dix-neuf',
      20: 'vingt',
      21: 'vingt et un',
      22: 'vingt-deux',
      23: 'vingt-trois',
      24: 'vingt-quatre',
      25: 'vingt-cinq',
      26: 'vingt-six',
      27: 'vingt-sept',
      28: 'vingt-huit',
      29: 'vingt-neuf',
      30: 'trente',
      31: 'trente et un',
      32: 'trente-deux',
    },
    tempTemplates: [
      'mets la température à {n} degrés',
      'règle la température sur {n}',
      'mets {n} degrés',
      'température {n} degrés',
    ],
    fanTemplates: [
      'mets le ventilateur à {n}',
      'règle le ventilateur sur {n}',
      'vitesse du ventilateur {n}',
    ],
    titles: {
      CommandCategory.door: 'Portes',
      CommandCategory.window: 'Vitres',
      CommandCategory.climate: 'Climatisation',
      CommandCategory.comfort: 'Confort',
      CommandCategory.status: 'État',
      CommandCategory.apps: 'Applications',
    },
    labels: {
      'door.lock': 'Verrouiller',
      'door.unlock': 'Déverrouiller',
      'door.trunk.open': 'Ouvrir le coffre',
      'window.fl.open': 'Vitre avant gauche ouvrir',
      'window.fl.close': 'Vitre avant gauche fermer',
      'window.fl.down': 'Vitre avant gauche descendre',
      'window.fr.open': 'Vitre avant droite ouvrir',
      'window.fr.close': 'Vitre avant droite fermer',
      'window.rl.open': 'Vitre arrière gauche ouvrir',
      'window.rl.close': 'Vitre arrière gauche fermer',
      'window.rr.open': 'Vitre arrière droite ouvrir',
      'window.rr.close': 'Vitre arrière droite fermer',
      'climate.power': 'Climatisation marche/arrêt',
      'climate.defrost_f': 'Dégivrage avant',
      'climate.defrost_r': 'Dégivrage arrière',
      'climate.max_hot': 'Chaleur maximum',
      'climate.max_cool': 'Climatisation maximum',
      'climate.compressor': 'Compresseur',
      'climate.temp': 'Température',
      'climate.fan': 'Ventilateur',
      'comfort.frag.off': 'Désactiver le parfum',
    },
  ),

  // ── Spanish ──────────────────────────────────────────────────────────────
  'es': VoiceLangPack(
    commands: {
      'window_down': ['baja la ventana', 'ventana abajo del todo'],
      'window_fr_open': [
        'abre la ventana del copiloto',
        'ventana delantera derecha abre',
      ],
      'window_fr_close': [
        'cierra la ventana del copiloto',
        'ventana delantera derecha cierra',
      ],
      'window_rl_open': [
        'abre la ventana trasera izquierda',
        'ventana trasera izquierda abre',
      ],
      'window_rl_close': [
        'cierra la ventana trasera izquierda',
        'ventana trasera izquierda cierra',
      ],
      'window_rr_open': [
        'abre la ventana trasera derecha',
        'ventana trasera derecha abre',
      ],
      'window_rr_close': [
        'cierra la ventana trasera derecha',
        'ventana trasera derecha cierra',
      ],
      'defrost_off': [
        'apaga el desempañador delantero',
        'desempañador delantero apaga',
      ],
      'defrost_rear': [
        'enciende el desempañador trasero',
        'desempañador trasero enciende',
      ],
      'defrost_rear_off': [
        'apaga el desempañador trasero',
        'desempañador trasero apaga',
      ],
      'max_hot': ['temperatura máxima', 'máximo calor'],
      'max_cool': ['máximo frío', 'aire al máximo'],
      'compressor_on': ['enciende el compresor', 'activa el compresor'],
      'compressor_off': ['apaga el compresor', 'desactiva el compresor'],
      'fragrance_off': ['apaga el difusor', 'apaga el ambientador'],
    },
    numberWords: {
      0: 'cero',
      1: 'uno',
      2: 'dos',
      3: 'tres',
      4: 'cuatro',
      5: 'cinco',
      6: 'seis',
      7: 'siete',
      16: 'dieciséis',
      17: 'diecisiete',
      18: 'dieciocho',
      19: 'diecinueve',
      20: 'veinte',
      21: 'veintiuno',
      22: 'veintidós',
      23: 'veintitrés',
      24: 'veinticuatro',
      25: 'veinticinco',
      26: 'veintiséis',
      27: 'veintisiete',
      28: 'veintiocho',
      29: 'veintinueve',
      30: 'treinta',
      31: 'treinta y uno',
      32: 'treinta y dos',
    },
    tempTemplates: [
      'pon la temperatura a {n} grados',
      'temperatura a {n}',
      'sube la temperatura a {n} grados',
      'baja la temperatura a {n} grados',
    ],
    fanTemplates: [
      'pon el ventilador a {n}',
      'ventilador nivel {n}',
      'velocidad del ventilador {n}',
    ],
    titles: {
      CommandCategory.door: 'Puertas',
      CommandCategory.window: 'Ventanas',
      CommandCategory.climate: 'Clima',
      CommandCategory.comfort: 'Confort',
      CommandCategory.status: 'Estado',
      CommandCategory.apps: 'Aplicaciones',
    },
    labels: {
      'door.lock': 'Bloquear',
      'door.unlock': 'Desbloquear',
      'door.trunk.open': 'Abrir maletero',
      'window.fl.open': 'Abrir delantera izquierda',
      'window.fl.close': 'Cerrar delantera izquierda',
      'window.fl.down': 'Bajar delantera izquierda',
      'window.fr.open': 'Abrir delantera derecha',
      'window.fr.close': 'Cerrar delantera derecha',
      'window.rl.open': 'Abrir trasera izquierda',
      'window.rl.close': 'Cerrar trasera izquierda',
      'window.rr.open': 'Abrir trasera derecha',
      'window.rr.close': 'Cerrar trasera derecha',
      'climate.power': 'Encender clima',
      'climate.defrost_f': 'Desempañador delantero',
      'climate.defrost_r': 'Desempañador trasero',
      'climate.max_hot': 'Máximo calor',
      'climate.max_cool': 'Máximo frío',
      'climate.compressor': 'Compresor',
      'climate.temp': 'Temperatura',
      'climate.fan': 'Ventilador',
      'comfort.frag.off': 'Apagar difusor',
    },
  ),

  // ── German ───────────────────────────────────────────────────────────────
  'de': VoiceLangPack(
    commands: {
      'window_down': ['fenster ganz runter', 'fahrerfenster komplett öffnen'],
      'window_fr_open': ['beifahrerfenster öffnen', 'vorne rechts fenster auf'],
      'window_fr_close': [
        'beifahrerfenster schließen',
        'vorne rechts fenster zu',
      ],
      'window_rl_open': [
        'hinten links fenster öffnen',
        'hinteres linkes fenster auf',
      ],
      'window_rl_close': [
        'hinten links fenster schließen',
        'hinteres linkes fenster zu',
      ],
      'window_rr_open': [
        'hinten rechts fenster öffnen',
        'hinteres rechtes fenster auf',
      ],
      'window_rr_close': [
        'hinten rechts fenster schließen',
        'hinteres rechtes fenster zu',
      ],
      'defrost_off': [
        'frontscheibenheizung aus',
        'scheibenentfrostung vorne aus',
      ],
      'defrost_rear': ['heckscheibenheizung an', 'heckentfrostung einschalten'],
      'defrost_rear_off': [
        'heckscheibenheizung aus',
        'heckentfrostung ausschalten',
      ],
      'max_hot': ['maximale heizung', 'volle wärme'],
      'max_cool': ['maximale kühlung', 'volle klimaanlage'],
      'compressor_on': ['kompressor einschalten', 'klimakompressor an'],
      'compressor_off': ['kompressor ausschalten', 'klimakompressor aus'],
      'fragrance_off': ['duft ausschalten', 'duftdiffusor aus'],
    },
    numberWords: {
      0: 'null',
      1: 'eins',
      2: 'zwei',
      3: 'drei',
      4: 'vier',
      5: 'fünf',
      6: 'sechs',
      7: 'sieben',
      16: 'sechzehn',
      17: 'siebzehn',
      18: 'achtzehn',
      19: 'neunzehn',
      20: 'zwanzig',
      21: 'einundzwanzig',
      22: 'zweiundzwanzig',
      23: 'dreiundzwanzig',
      24: 'vierundzwanzig',
      25: 'fünfundzwanzig',
      26: 'sechsundzwanzig',
      27: 'siebenundzwanzig',
      28: 'achtundzwanzig',
      29: 'neunundzwanzig',
      30: 'dreißig',
      31: 'einunddreißig',
      32: 'zweiunddreißig',
    },
    tempTemplates: ['temperatur auf {n} grad', 'stell {n} grad ein'],
    fanTemplates: ['lüfterstufe {n}', 'gebläse auf stufe {n}'],
    titles: {
      CommandCategory.door: 'Türen',
      CommandCategory.window: 'Fenster',
      CommandCategory.climate: 'Klima',
      CommandCategory.comfort: 'Komfort',
      CommandCategory.status: 'Status',
      CommandCategory.apps: 'Apps',
    },
    labels: {
      'door.lock': 'Verriegeln',
      'door.unlock': 'Entriegeln',
      'door.trunk.open': 'Kofferraum öffnen',
      'window.fl.open': 'Vorne links öffnen',
      'window.fl.close': 'Vorne links schließen',
      'window.fl.down': 'Vorne links ganz runter',
      'window.fr.open': 'Vorne rechts öffnen',
      'window.fr.close': 'Vorne rechts schließen',
      'window.rl.open': 'Hinten links öffnen',
      'window.rl.close': 'Hinten links schließen',
      'window.rr.open': 'Hinten rechts öffnen',
      'window.rr.close': 'Hinten rechts schließen',
      'climate.power': 'Klima Ein/Aus',
      'climate.defrost_f': 'Frontentfrostung',
      'climate.defrost_r': 'Heckentfrostung',
      'climate.max_hot': 'Max Heizung',
      'climate.max_cool': 'Max Kühlung',
      'climate.compressor': 'Kompressor',
      'climate.temp': 'Temperatur',
      'climate.fan': 'Gebläse',
      'comfort.frag.off': 'Duft aus',
    },
  ),

  // ── Chinese (Simplified) ──────────────────────────────────────────────────
  'cn': VoiceLangPack(
    commands: {
      'window_down': ['车窗全部打开', '把车窗降下来'],
      'window_fr_open': ['打开副驾车窗', '副驾窗户打开'],
      'window_fr_close': ['关闭副驾车窗', '副驾窗户关上'],
      'window_rl_open': ['打开左后车窗', '左后窗户打开'],
      'window_rl_close': ['关闭左后车窗', '左后窗户关上'],
      'window_rr_open': ['打开右后车窗', '右后窗户打开'],
      'window_rr_close': ['关闭右后车窗', '右后窗户关上'],
      'defrost_off': ['关闭前除霜', '前挡风除霜关掉'],
      'defrost_rear': ['打开后除霜', '开启后窗除霜'],
      'defrost_rear_off': ['关闭后除霜', '后窗除霜关掉'],
      'max_hot': ['最热模式', '开最大暖风'],
      'max_cool': ['最冷模式', '开最大冷风'],
      'compressor_on': ['打开压缩机', '开启空调压缩机'],
      'compressor_off': ['关闭压缩机', '关掉空调压缩机'],
      'fragrance_off': ['关闭香氛', '香薰关掉'],
    },
    numberWords: {
      0: '零',
      1: '一',
      2: '二',
      3: '三',
      4: '四',
      5: '五',
      6: '六',
      7: '七',
      16: '十六',
      17: '十七',
      18: '十八',
      19: '十九',
      20: '二十',
      21: '二十一',
      22: '二十二',
      23: '二十三',
      24: '二十四',
      25: '二十五',
      26: '二十六',
      27: '二十七',
      28: '二十八',
      29: '二十九',
      30: '三十',
      31: '三十一',
      32: '三十二',
    },
    tempTemplates: ['把温度调到{n}度', '温度设置{n}度', '调到{n}度', '温度{n}度'],
    fanTemplates: ['风速调到{n}档', '风量{n}档', '风速{n}'],
    titles: {
      CommandCategory.door: '车门',
      CommandCategory.window: '车窗',
      CommandCategory.climate: '空调',
      CommandCategory.comfort: '舒适',
      CommandCategory.status: '状态',
      CommandCategory.apps: '应用',
    },
    labels: {
      'door.lock': '锁车',
      'door.unlock': '解锁',
      'door.trunk.open': '开后备箱',
      'window.fl.open': '开主驾车窗',
      'window.fl.close': '关主驾车窗',
      'window.fl.down': '降主驾车窗',
      'window.fr.open': '开副驾车窗',
      'window.fr.close': '关副驾车窗',
      'window.rl.open': '开左后车窗',
      'window.rl.close': '关左后车窗',
      'window.rr.open': '开右后车窗',
      'window.rr.close': '关右后车窗',
      'climate.power': '空调开关',
      'climate.defrost_f': '前除霜',
      'climate.defrost_r': '后除霜',
      'climate.max_hot': '最热',
      'climate.max_cool': '最冷',
      'climate.compressor': '压缩机',
      'climate.temp': '温度',
      'climate.fan': '风速',
      'comfort.frag.off': '关香氛',
    },
  ),

  // ── Turkish ───────────────────────────────────────────────────────────────
  'tr': VoiceLangPack(
    commands: {
      'window_down': ['camı tamamen indir', 'camı aç'],
      'window_fr_open': ['ön sağ camı aç', 'sağ ön camı aç'],
      'window_fr_close': ['ön sağ camı kapat', 'sağ ön camı kapat'],
      'window_rl_open': ['arka sol camı aç', 'sol arka camı aç'],
      'window_rl_close': ['arka sol camı kapat', 'sol arka camı kapat'],
      'window_rr_open': ['arka sağ camı aç', 'sağ arka camı aç'],
      'window_rr_close': ['arka sağ camı kapat', 'sağ arka camı kapat'],
      'defrost_off': ['ön buzu kapat', 'ön buz çözmeyi kapat'],
      'defrost_rear': ['arka buz çözmeyi aç', 'arka camı ısıt'],
      'defrost_rear_off': ['arka buz çözmeyi kapat', 'arka ısıtmayı kapat'],
      'max_hot': ['maksimum ısıtma', 'tam ısıtma'],
      'max_cool': ['maksimum soğutma', 'tam klima'],
      'compressor_on': ['kompresörü aç'],
      'compressor_off': ['kompresörü kapat'],
      'fragrance_off': ['kokuyu kapat', 'parfümü kapat'],
    },
    numberWords: {
      0: 'sıfır',
      1: 'bir',
      2: 'iki',
      3: 'üç',
      4: 'dört',
      5: 'beş',
      6: 'altı',
      7: 'yedi',
      16: 'on altı',
      17: 'on yedi',
      18: 'on sekiz',
      19: 'on dokuz',
      20: 'yirmi',
      21: 'yirmi bir',
      22: 'yirmi iki',
      23: 'yirmi üç',
      24: 'yirmi dört',
      25: 'yirmi beş',
      26: 'yirmi altı',
      27: 'yirmi yedi',
      28: 'yirmi sekiz',
      29: 'yirmi dokuz',
      30: 'otuz',
      31: 'otuz bir',
      32: 'otuz iki',
    },
    tempTemplates: ['sıcaklığı {n} yap', 'sıcaklığı {n} dereceye ayarla'],
    fanTemplates: ['fanı {n} yap', 'fan hızını {n} yap'],
    titles: {
      CommandCategory.door: 'Kapılar',
      CommandCategory.window: 'Camlar',
      CommandCategory.climate: 'İklim',
      CommandCategory.comfort: 'Konfor',
      CommandCategory.status: 'Durum',
      CommandCategory.apps: 'Uygulamalar',
    },
    labels: {
      'door.lock': 'Kilitle',
      'door.unlock': 'Kilidi Aç',
      'door.trunk.open': 'Bagajı Aç',
      'window.fl.open': 'Sol Ön Camı Aç',
      'window.fl.close': 'Sol Ön Camı Kapat',
      'window.fl.down': 'Sol Ön Camı İndir',
      'window.fr.open': 'Sağ Ön Camı Aç',
      'window.fr.close': 'Sağ Ön Camı Kapat',
      'window.rl.open': 'Sol Arka Camı Aç',
      'window.rl.close': 'Sol Arka Camı Kapat',
      'window.rr.open': 'Sağ Arka Camı Aç',
      'window.rr.close': 'Sağ Arka Camı Kapat',
      'climate.power': 'İklim Gücü',
      'climate.defrost_f': 'Ön Buz Çözme',
      'climate.defrost_r': 'Arka Buz Çözme',
      'climate.max_hot': 'Maks Isıtma',
      'climate.max_cool': 'Maks Soğutma',
      'climate.compressor': 'Kompresör',
      'climate.temp': 'Sıcaklık',
      'climate.fan': 'Fan Hızı',
      'comfort.frag.off': 'Kokuyu Kapat',
    },
  ),

  // ── Persian / Farsi ───────────────────────────────────────────────────────
  'fa': VoiceLangPack(
    commands: {
      'window_down': ['شیشه را کامل پایین بیار', 'شیشه راننده کامل پایین'],
      'window_fr_open': ['شیشه جلو راست را باز کن', 'شیشه صندلی جلو باز کن'],
      'window_fr_close': ['شیشه جلو راست را ببند', 'شیشه صندلی جلو ببند'],
      'window_rl_open': ['شیشه عقب چپ را باز کن', 'شیشه عقب سمت راننده باز کن'],
      'window_rl_close': ['شیشه عقب چپ را ببند', 'شیشه عقب سمت راننده ببند'],
      'window_rr_open': [
        'شیشه عقب راست را باز کن',
        'شیشه عقب سمت شاگرد باز کن',
      ],
      'window_rr_close': ['شیشه عقب راست را ببند', 'شیشه عقب سمت شاگرد ببند'],
      'defrost_off': ['گرمکن شیشه جلو را خاموش کن', 'دیفراست جلو خاموش'],
      'defrost_rear': ['گرمکن شیشه عقب را روشن کن', 'دیفراست عقب روشن'],
      'defrost_rear_off': ['گرمکن شیشه عقب را خاموش کن', 'دیفراست عقب خاموش'],
      'max_hot': ['حداکثر گرما', 'بخاری را حداکثر کن'],
      'max_cool': ['حداکثر سرما', 'کولر را حداکثر کن'],
      'compressor_on': ['کمپرسور را روشن کن'],
      'compressor_off': ['کمپرسور را خاموش کن'],
      'fragrance_off': ['خوشبوکننده را خاموش کن', 'عطرپاش خاموش'],
    },
    numberWords: {
      0: 'صفر',
      1: 'یک',
      2: 'دو',
      3: 'سه',
      4: 'چهار',
      5: 'پنج',
      6: 'شش',
      7: 'هفت',
      16: 'شانزده',
      17: 'هفده',
      18: 'هجده',
      19: 'نوزده',
      20: 'بیست',
      21: 'بیست و یک',
      22: 'بیست و دو',
      23: 'بیست و سه',
      24: 'بیست و چهار',
      25: 'بیست و پنج',
      26: 'بیست و شش',
      27: 'بیست و هفت',
      28: 'بیست و هشت',
      29: 'بیست و نه',
      30: 'سی',
      31: 'سی و یک',
      32: 'سی و دو',
    },
    tempTemplates: ['دما را {n} درجه کن', 'درجه حرارت را بذار روی {n}'],
    fanTemplates: ['سرعت فن را {n} کن', 'فن را بذار روی {n}'],
    titles: {
      CommandCategory.door: 'درب',
      CommandCategory.window: 'شیشه',
      CommandCategory.climate: 'آب و هوا',
      CommandCategory.comfort: 'راحتی',
      CommandCategory.status: 'وضعیت',
      CommandCategory.apps: 'برنامه‌ها',
    },
    labels: {
      'door.lock': 'قفل درب',
      'door.unlock': 'قفل باز',
      'door.trunk.open': 'باز کردن صندوق عقب',
      'window.fl.open': 'باز کردن شیشه جلو چپ',
      'window.fl.close': 'بستن شیشه جلو چپ',
      'window.fl.down': 'پایین آوردن شیشه جلو چپ',
      'window.fr.open': 'باز کردن شیشه جلو راست',
      'window.fr.close': 'بستن شیشه جلو راست',
      'window.rl.open': 'باز کردن شیشه عقب چپ',
      'window.rl.close': 'بستن شیشه عقب چپ',
      'window.rr.open': 'باز کردن شیشه عقب راست',
      'window.rr.close': 'بستن شیشه عقب راست',
      'climate.power': 'روشن خاموش',
      'climate.defrost_f': 'گرمکن جلو',
      'climate.defrost_r': 'گرمکن عقب',
      'climate.max_hot': 'حداکثر گرما',
      'climate.max_cool': 'حداکثر سرما',
      'climate.compressor': 'کمپرسور',
      'climate.temp': 'دما',
      'climate.fan': 'فن',
      'comfort.frag.off': 'خاموش کردن خوشبوکننده',
    },
  ),

  // ── Hindi ─────────────────────────────────────────────────────────────────
  'hi': VoiceLangPack(
    commands: {
      'window_down': ['खिड़की पूरी नीचे करो', 'शीशा नीचे करो'],
      'window_fr_open': ['आगे दाईं खिड़की खोलो', 'सामने दाईं तरफ शीशा खोलो'],
      'window_fr_close': [
        'आगे दाईं खिड़की बंद करो',
        'सामने दाईं तरफ शीशा बंद करो',
      ],
      'window_rl_open': ['पीछे बाईं खिड़की खोलो', 'पीछे बाईं तरफ शीशा खोलो'],
      'window_rl_close': [
        'पीछे बाईं खिड़की बंद करो',
        'पीछे बाईं तरफ शीशा बंद करो',
      ],
      'window_rr_open': ['पीछे दाईं खिड़की खोलो', 'पीछे दाईं तरफ शीशा खोलो'],
      'window_rr_close': [
        'पीछे दाईं खिड़की बंद करो',
        'पीछे दाईं तरफ शीशा बंद करो',
      ],
      'defrost_off': ['आगे का डिफ्रॉस्ट बंद करो', 'सामने का डिफ्रॉस्ट बंद करो'],
      'defrost_rear': [
        'पीछे का डिफ्रॉस्ट चालू करो',
        'पिछली खिड़की डिफ्रॉस्ट चालू करो',
      ],
      'defrost_rear_off': [
        'पीछे का डिफ्रॉस्ट बंद करो',
        'पिछली खिड़की डिफ्रॉस्ट बंद करो',
      ],
      'max_hot': ['पूरी गर्मी चालू करो', 'मैक्स हीट चालू करो'],
      'max_cool': ['पूरी ठंडक चालू करो', 'मैक्स एसी चालू करो'],
      'compressor_on': ['कंप्रेसर चालू करो', 'एसी कंप्रेसर चालू करो'],
      'compressor_off': ['कंप्रेसर बंद करो', 'एसी कंप्रेसर बंद करो'],
      'fragrance_off': ['खुशबू बंद करो', 'फ्रेगरेंस बंद करो'],
    },
    numberWords: {
      0: 'शून्य',
      1: 'एक',
      2: 'दो',
      3: 'तीन',
      4: 'चार',
      5: 'पाँच',
      6: 'छह',
      7: 'सात',
      16: 'सोलह',
      17: 'सत्रह',
      18: 'अठारह',
      19: 'उन्नीस',
      20: 'बीस',
      21: 'इक्कीस',
      22: 'बाईस',
      23: 'तेईस',
      24: 'चौबीस',
      25: 'पच्चीस',
      26: 'छब्बीस',
      27: 'सत्ताईस',
      28: 'अट्ठाईस',
      29: 'उनतीस',
      30: 'तीस',
      31: 'इकतीस',
      32: 'बत्तीस',
    },
    tempTemplates: ['तापमान {n} डिग्री करो', 'एसी {n} डिग्री पर लगाओ'],
    fanTemplates: ['पंखा {n} पर लगाओ', 'फैन स्पीड {n} करो'],
    titles: {
      CommandCategory.door: 'दरवाज़ा',
      CommandCategory.window: 'खिड़की',
      CommandCategory.climate: 'जलवायु',
      CommandCategory.comfort: 'आराम',
      CommandCategory.status: 'स्थिति',
      CommandCategory.apps: 'ऐप्स',
    },
    labels: {
      'door.lock': 'लॉक',
      'door.unlock': 'अनलॉक',
      'door.trunk.open': 'डिक्की खोलो',
      'window.fl.open': 'ड्राइवर खिड़की खोलो',
      'window.fl.close': 'ड्राइवर खिड़की बंद करो',
      'window.fl.down': 'ड्राइवर खिड़की नीचे करो',
      'window.fr.open': 'आगे दाईं खिड़की खोलो',
      'window.fr.close': 'आगे दाईं खिड़की बंद करो',
      'window.rl.open': 'पीछे बाईं खिड़की खोलो',
      'window.rl.close': 'पीछे बाईं खिड़की बंद करो',
      'window.rr.open': 'पीछे दाईं खिड़की खोलो',
      'window.rr.close': 'पीछे दाईं खिड़की बंद करो',
      'climate.power': 'एसी चालू / बंद',
      'climate.defrost_f': 'आगे डिफ्रॉस्ट',
      'climate.defrost_r': 'पीछे डिफ्रॉस्ट',
      'climate.max_hot': 'मैक्स हीट',
      'climate.max_cool': 'मैक्स कूल',
      'climate.compressor': 'कंप्रेसर',
      'climate.temp': 'तापमान',
      'climate.fan': 'पंखा',
      'comfort.frag.off': 'खुशबू बंद',
    },
  ),

  // ── Italian ───────────────────────────────────────────────────────────────
  'it': VoiceLangPack(
    commands: {
      'window_down': ['abbassa il finestrino', 'finestrino giù'],
      'window_fr_open': [
        'apri il finestrino anteriore destro',
        'finestrino passeggero apri',
      ],
      'window_fr_close': [
        'chiudi il finestrino anteriore destro',
        'finestrino passeggero chiudi',
      ],
      'window_rl_open': [
        'apri il finestrino posteriore sinistro',
        'finestrino dietro sinistra apri',
      ],
      'window_rl_close': [
        'chiudi il finestrino posteriore sinistro',
        'finestrino dietro sinistra chiudi',
      ],
      'window_rr_open': [
        'apri il finestrino posteriore destro',
        'finestrino dietro destra apri',
      ],
      'window_rr_close': [
        'chiudi il finestrino posteriore destro',
        'finestrino dietro destra chiudi',
      ],
      'defrost_off': [
        'spegni il disappannamento',
        'disattiva il disappannamento anteriore',
      ],
      'defrost_rear': [
        'attiva il disappannamento posteriore',
        'scalda il lunotto',
      ],
      'defrost_rear_off': [
        'spegni il disappannamento posteriore',
        'disattiva il lunotto termico',
      ],
      'max_hot': ['riscaldamento massimo', 'temperatura massima'],
      'max_cool': ['raffreddamento massimo', 'aria condizionata al massimo'],
      'compressor_on': ['accendi il compressore', 'attiva il compressore'],
      'compressor_off': ['spegni il compressore', 'disattiva il compressore'],
      'fragrance_off': ['spegni il profumatore', 'disattiva il diffusore'],
    },
    numberWords: {
      0: 'zero',
      1: 'uno',
      2: 'due',
      3: 'tre',
      4: 'quattro',
      5: 'cinque',
      6: 'sei',
      7: 'sette',
      16: 'sedici',
      17: 'diciassette',
      18: 'diciotto',
      19: 'diciannove',
      20: 'venti',
      21: 'ventuno',
      22: 'ventidue',
      23: 'ventitre',
      24: 'ventiquattro',
      25: 'venticinque',
      26: 'ventisei',
      27: 'ventisette',
      28: 'ventotto',
      29: 'ventinove',
      30: 'trenta',
      31: 'trentuno',
      32: 'trentadue',
    },
    tempTemplates: ['imposta la temperatura a {n} gradi', 'metti {n} gradi'],
    fanTemplates: ['imposta il ventilatore a {n}', 'velocità ventola {n}'],
    titles: {
      CommandCategory.door: 'Porte',
      CommandCategory.window: 'Finestrini',
      CommandCategory.climate: 'Clima',
      CommandCategory.comfort: 'Comfort',
      CommandCategory.status: 'Stato',
      CommandCategory.apps: 'App',
    },
    labels: {
      'door.lock': 'Blocca',
      'door.unlock': 'Sblocca',
      'door.trunk.open': 'Apri bagagliaio',
      'window.fl.open': 'Apri ant. sin.',
      'window.fl.close': 'Chiudi ant. sin.',
      'window.fl.down': 'Abbassa ant. sin.',
      'window.fr.open': 'Apri ant. des.',
      'window.fr.close': 'Chiudi ant. des.',
      'window.rl.open': 'Apri post. sin.',
      'window.rl.close': 'Chiudi post. sin.',
      'window.rr.open': 'Apri post. des.',
      'window.rr.close': 'Chiudi post. des.',
      'climate.power': 'Clima on/off',
      'climate.defrost_f': 'Disappannamento ant.',
      'climate.defrost_r': 'Lunotto termico',
      'climate.max_hot': 'Caldo max',
      'climate.max_cool': 'Freddo max',
      'climate.compressor': 'Compressore',
      'climate.temp': 'Temperatura',
      'climate.fan': 'Ventola',
      'comfort.frag.off': 'Spegni profumatore',
    },
  ),

  // ── Portuguese (Brazilian) ────────────────────────────────────────────────
  'pt': VoiceLangPack(
    commands: {
      'window_down': ['abre a janela toda', 'janela toda aberta'],
      'window_fr_open': [
        'abre a janela do passageiro',
        'abre a janela da frente direita',
      ],
      'window_fr_close': [
        'fecha a janela do passageiro',
        'fecha a janela da frente direita',
      ],
      'window_rl_open': [
        'abre a janela traseira esquerda',
        'abre a janela de trás esquerda',
      ],
      'window_rl_close': [
        'fecha a janela traseira esquerda',
        'fecha a janela de trás esquerda',
      ],
      'window_rr_open': [
        'abre a janela traseira direita',
        'abre a janela de trás direita',
      ],
      'window_rr_close': [
        'fecha a janela traseira direita',
        'fecha a janela de trás direita',
      ],
      'defrost_off': [
        'desliga o desembaçador dianteiro',
        'desliga o desembaçador da frente',
      ],
      'defrost_rear': [
        'liga o desembaçador traseiro',
        'desembaça o vidro de trás',
      ],
      'defrost_rear_off': [
        'desliga o desembaçador traseiro',
        'desliga o desembaçador de trás',
      ],
      'max_hot': ['temperatura máxima', 'calor máximo'],
      'max_cool': ['refrigeração máxima', 'ar condicionado máximo'],
      'compressor_on': ['liga o compressor'],
      'compressor_off': ['desliga o compressor'],
      'fragrance_off': ['desliga o difusor', 'desliga a fragrância'],
    },
    numberWords: {
      0: 'zero',
      1: 'um',
      2: 'dois',
      3: 'três',
      4: 'quatro',
      5: 'cinco',
      6: 'seis',
      7: 'sete',
      16: 'dezesseis',
      17: 'dezessete',
      18: 'dezoito',
      19: 'dezenove',
      20: 'vinte',
      21: 'vinte e um',
      22: 'vinte e dois',
      23: 'vinte e três',
      24: 'vinte e quatro',
      25: 'vinte e cinco',
      26: 'vinte e seis',
      27: 'vinte e sete',
      28: 'vinte e oito',
      29: 'vinte e nove',
      30: 'trinta',
      31: 'trinta e um',
      32: 'trinta e dois',
    },
    tempTemplates: [
      'coloca a temperatura em {n} graus',
      'temperatura {n} graus',
    ],
    fanTemplates: ['velocidade do ventilador {n}', 'ventilador nível {n}'],
    titles: {
      CommandCategory.door: 'Portas',
      CommandCategory.window: 'Janelas',
      CommandCategory.climate: 'Climatização',
      CommandCategory.comfort: 'Conforto',
      CommandCategory.status: 'Status',
      CommandCategory.apps: 'Aplicativos',
    },
    labels: {
      'door.lock': 'Trancar',
      'door.unlock': 'Destrancar',
      'door.trunk.open': 'Abrir porta-malas',
      'window.fl.open': 'Abrir esquerda dianteira',
      'window.fl.close': 'Fechar esquerda dianteira',
      'window.fl.down': 'Baixar esquerda dianteira',
      'window.fr.open': 'Abrir direita dianteira',
      'window.fr.close': 'Fechar direita dianteira',
      'window.rl.open': 'Abrir esquerda traseira',
      'window.rl.close': 'Fechar esquerda traseira',
      'window.rr.open': 'Abrir direita traseira',
      'window.rr.close': 'Fechar direita traseira',
      'climate.power': 'Ligar/Desligar',
      'climate.defrost_f': 'Desembaçador dianteiro',
      'climate.defrost_r': 'Desembaçador traseiro',
      'climate.max_hot': 'Calor máximo',
      'climate.max_cool': 'Frio máximo',
      'climate.compressor': 'Compressor',
      'climate.temp': 'Temperatura',
      'climate.fan': 'Ventilador',
      'comfort.frag.off': 'Desligar fragrância',
    },
  ),
};
