package com.i99dev.ilink.car

// GENERATED — do not edit by hand.
// Source of truth: lib/sdk/brands/byd/byd_status_facet.dart (deviceType +
// valueKind) + byd_catalog.dart (label -> framework). Regenerate with:
//   dart run tool/gen_status_key_catalog.dart
// CI fails if this file drifts from a fresh generation.

/**
 * Status-key catalog — the labels the daemon actively reads/pushes, each
 * with its BYD `device_type`, `featureName` (resolved at boot via
 * BydAutoFeatureIdsCatalog) and `valueKind`.
 *
 * Cross-trim safe by construction — names that don't resolve on a given
 * trim are silently dropped by [build].
 */
object StatusKeyCatalog {

    private data class RawEntry(
        val label: String,
        val deviceType: Int,
        val featureName: String,
        val valueKind: ValueKind,
    )

    private enum class ValueKind { INT, DOUBLE, BYTES, INT_ARRAY }

    private val raw: List<RawEntry> = listOf(
        RawEntry("door_lock", 1001, "Door.DOOR_LOCK_COMMAND_AREA_LEFT_FRONT", ValueKind.INT),
        RawEntry("door_lf", 1001, "Bodywork.BODYWORK_LEFT_HAND_FRONT_DOOR", ValueKind.INT),
        RawEntry("door_rf", 1001, "Bodywork.BODYWORK_RIGHT_HAND_FRONT_DOOR", ValueKind.INT),
        RawEntry("door_lr", 1001, "Bodywork.BODYWORK_LEFT_HAND_REAR_DOOR", ValueKind.INT),
        RawEntry("door_rr", 1001, "Bodywork.BODYWORK_RIGHT_HAND_REAR_DOOR", ValueKind.INT),
        RawEntry("trunk", 1001, "Bodywork.BODYWORK_LUGGAGE_DOOR", ValueKind.INT),
        RawEntry("ac_power", 1000, "Ac.AC_POWER_STATE", ValueKind.INT),
        RawEntry("ac_fan", 1000, "Ac.AC_WIND_LEVEL", ValueKind.INT),
        RawEntry("ac_wind_mode", 1000, "Ac.AC_WIND_MODE", ValueKind.INT),
        RawEntry("ac_cycle", 1000, "Ac.AC_CYCLE_MODE", ValueKind.INT),
        RawEntry("ac_target_temp", 1000, "Ac.AC_TEMP_MAIN", ValueKind.INT),
        RawEntry("ac_cabin_temp", 1000, "Ac.AC_TEMP_INSIDE", ValueKind.INT),
        RawEntry("ac_temp_out", 1001, "Instrument.INSTRUMENT_DD_OUT_TEMP", ValueKind.INT),
        RawEntry("headlight", 1001, "Instrument.INSTRUMENT_SMART_KEY_SYS_WARN_LIGHT", ValueKind.INT),
        RawEntry("low_beam", 1001, "Light.LIGHT_LOW_BEAM_LIGHT", ValueKind.INT),
        RawEntry("high_beam", 1001, "Light.LIGHT_HIGH_BEAM_LIGHT", ValueKind.INT),
        RawEntry("front_fog", 1001, "Light.LIGHT_FRONT_FOG_LIGHT", ValueKind.INT),
        RawEntry("rear_fog", 1001, "Light.LIGHT_REAR_FOG_LIGHT", ValueKind.INT),
        RawEntry("battery_pct", 1001, "Statistic.STATISTIC_SOC_BATTERY_PERCENTAGE", ValueKind.INT),
        RawEntry("range_ev_km", 1001, "Statistic.STATISTIC_ELEC_DRIVING_RANGE", ValueKind.INT),
        RawEntry("range_fuel_km", 1001, "Statistic.STATISTIC_FUEL_DRIVING_RANGE", ValueKind.INT),
        RawEntry("ev_mode", 1001, "Instrument.INSTRUMENT_EV_MODE_INDICATORE", ValueKind.INT),
        RawEntry("hev_mode", 1001, "Instrument.INSTRUMENT_HEV_MODE_INDICATORE", ValueKind.INT),
        RawEntry("speed_kmh", 1001, "Statistic.STATISTIC_SPEED_SIG_VDIS", ValueKind.INT),
        RawEntry("sunroof_state", 1001, "Bodywork.BODYWORK_SUNROOF_STATE", ValueKind.INT),
        RawEntry("sunroof_position", 1001, "Bodywork.BODYWORK_SUNROOF_POSITION", ValueKind.INT),
        RawEntry("lock_lf", 1001, "Door.DOOR_LOCK_COMMAND_AREA_LEFT_FRONT", ValueKind.INT),
        RawEntry("lock_rf", 1001, "Door.DOOR_LOCK_COMMAND_AREA_RIGHT_FRONT", ValueKind.INT),
        RawEntry("lock_lr", 1001, "Door.DOOR_LOCK_COMMAND_AREA_LEFT_REAR", ValueKind.INT),
        RawEntry("lock_rr", 1001, "Door.DOOR_LOCK_COMMAND_AREA_RIGHT_REAR", ValueKind.INT),
        RawEntry("lock_back", 1001, "Door.DOOR_LOCK_COMMAND_AREA_BACK", ValueKind.INT),
        RawEntry("child_lock_l", 1001, "Door.DOOR_LOCK_COMMAND_AREA_CHILDLOCK_LEFT", ValueKind.INT),
        RawEntry("child_lock_r", 1001, "Door.DOOR_LOCK_COMMAND_AREA_CHILDLOCK_RIGHT", ValueKind.INT),
        RawEntry("hood", 1001, "Bodywork.BODYWORK_HOOD", ValueKind.INT),
        RawEntry("fuel_cap", 1001, "Bodywork.BODYWORK_FUEL_TANK_CAP", ValueKind.INT),
        RawEntry("window_lf", 1001, "Bodywork.BODYWORK_LEFT_FRONT_WINDOW", ValueKind.INT),
        RawEntry("window_rf", 1001, "Bodywork.BODYWORK_RIGHT_FRONT_WINDOW", ValueKind.INT),
        RawEntry("window_lr", 1001, "Bodywork.BODYWORK_LEFT_REAR_WINDOW", ValueKind.INT),
        RawEntry("window_rr", 1001, "Bodywork.BODYWORK_RIGHT_REAR_WINDOW", ValueKind.INT),
        RawEntry("window_lf_pct", 1001, "Bodywork.BODYWORK_WINDOW_LEFT_FRONT_PERCENT", ValueKind.INT),
        RawEntry("window_rf_pct", 1001, "Bodywork.BODYWORK_WINDOW_RIGHT_FRONT_PERCENT", ValueKind.INT),
        RawEntry("window_lr_pct", 1001, "Bodywork.BODYWORK_WINDOW_LEFT_REAR_PERCENT", ValueKind.INT),
        RawEntry("window_rr_pct", 1001, "Bodywork.BODYWORK_WINDOW_RIGHT_REAR_PERCENT", ValueKind.INT),
        RawEntry("moon_roof", 1001, "Bodywork.BODYWORK_MOON_ROOF", ValueKind.INT),
        RawEntry("moon_roof_pct", 1001, "Bodywork.BODYWORK_MOON_ROOF_OPEN_PERCENT", ValueKind.INT),
        RawEntry("sunshade", 1001, "Bodywork.BODYWORK_SUNSHADE_PANEL", ValueKind.INT),
        RawEntry("sunshade_pct", 1001, "Bodywork.BODYWORK_SUNSHADE_PANEL_PERCENT", ValueKind.INT),
        RawEntry("rain_auto_close", 1001, "Bodywork.BODYWORK_CLOSE_WINDOW_FOR_RAIN_ONLINE", ValueKind.INT),
        RawEntry("ac_ctrl_mode", 1000, "Ac.AC_CTRL_MODE", ValueKind.INT),
        RawEntry("ac_compressor", 1000, "Ac.AC_COMPRESSOR_MODE", ValueKind.INT),
        RawEntry("ac_target_temp_co", 1000, "Ac.AC_TEMP_DEPUTY", ValueKind.INT),
        RawEntry("ac_target_temp_rear", 1000, "Ac.AC_TEMP_REAR", ValueKind.INT),
        RawEntry("ac_temp_unit", 1000, "Ac.AC_TEMPERATURE_UNIT", ValueKind.INT),
        RawEntry("ac_defrost_f", 1000, "Ac.AC_DEFROST_FRONT_STATE", ValueKind.INT),
        RawEntry("ac_defrost_r", 1000, "Ac.AC_DEFROST_REAR_STATE", ValueKind.INT),
        RawEntry("ac_max_cool", 1000, "Ac.AC_MAX_COOLING_STATE", ValueKind.INT),
        RawEntry("ac_vent", 1000, "Ac.AC_VENTILATION_STATE", ValueKind.INT),
        RawEntry("ac_rear_power", 1000, "Ac.AC_REAR_POWER_STATE", ValueKind.INT),
        RawEntry("ac_temp_separate", 1000, "Ac.AC_TEMPCTRL_SEPARATE_STATE", ValueKind.INT),
        RawEntry("ac_quick_clean", 1000, "Ac.AC_QUICK_CLEAN_AIR", ValueKind.INT),
        RawEntry("ac_auto_clean", 1000, "Ac.AC_AUTO_CLEAN_AIR", ValueKind.INT),
        RawEntry("turn_left", 1001, "Light.LIGHT_LEFT_TURN_SIGNAL_LIGHT", ValueKind.INT),
        RawEntry("turn_right", 1001, "Light.LIGHT_RIGHT_TURN_SIGNAL_LIGHT", ValueKind.INT),
        RawEntry("turn_signal", 1001, "Light.LIGHT_TURN_SIGNAL_LIGHT", ValueKind.INT),
        RawEntry("drl", 1001, "Light.LIGHT_DAY_RUNNING_LIGHT_AUTO_STATE", ValueKind.INT),
        RawEntry("foot_light", 1001, "Light.LIGHT_FOOT_LIGHT", ValueKind.INT),
        RawEntry("side_light", 1001, "Light.LIGHT_SIDE_LIGHT", ValueKind.INT),
        RawEntry("stalk_l", 1001, "Light.LIGHT_LEFT_TURN_SIGNAL_LIGHT_SWITCH_STATE", ValueKind.INT),
        RawEntry("stalk_r", 1001, "Light.LIGHT_RIGHT_TURN_SIGNAL_LIGHT_SWITCH_STATE", ValueKind.INT),
        RawEntry("tpms_pressure_lf", 1001, "Instrument.INSTRUMENT_2IN1_LF_TYRE_PRESSURE", ValueKind.DOUBLE),
        RawEntry("tpms_pressure_rf", 1001, "Instrument.INSTRUMENT_2IN1_RF_TYRE_PRESSURE", ValueKind.DOUBLE),
        RawEntry("tpms_pressure_lr", 1001, "Instrument.INSTRUMENT_2IN1_LB_TYRE_PRESSURE", ValueKind.DOUBLE),
        RawEntry("tpms_pressure_rr", 1001, "Instrument.INSTRUMENT_2IN1_RB_TYRE_PRESSURE", ValueKind.DOUBLE),
        RawEntry("tpms_temp_lf", 1001, "Instrument.INSTRUMENT_2IN1_LF_TYRE_TEMPERATURE", ValueKind.DOUBLE),
        RawEntry("tpms_temp_rf", 1001, "Instrument.INSTRUMENT_2IN1_RF_TYRE_TEMPERATURE", ValueKind.DOUBLE),
        RawEntry("tpms_temp_lr", 1001, "Instrument.INSTRUMENT_2IN1_LB_TYRE_TEMPERATURE", ValueKind.DOUBLE),
        RawEntry("tpms_temp_rr", 1001, "Instrument.INSTRUMENT_2IN1_RB_TYRE_TEMPERATURE", ValueKind.DOUBLE),
        RawEntry("chg_cap_ac", 1001, "Charging.CHARGING_CAP_STATE_AC", ValueKind.INT),
        RawEntry("chg_cap_dc", 1001, "Charging.CHARGING_CAP_STATE_DC", ValueKind.INT),
        RawEntry("chg_capacity", 1001, "Charging.CHARGING_CAPACITY", ValueKind.INT),
        RawEntry("chg_power", 1001, "Charging.CHARGING_POWER", ValueKind.INT),
        RawEntry("chg_work_state", 1001, "Charging.CHARGING_CHARGER_WORK_STATE", ValueKind.INT),
        RawEntry("chg_eta_h", 1001, "Charging.CHARGING_FULL_REST_HOUR", ValueKind.INT),
        RawEntry("chg_eta_m", 1001, "Charging.CHARGING_FULL_REST_MINUTE", ValueKind.INT),
        RawEntry("chg_soc_save", 1001, "Charging.CHARGING_SOC_SAVE_SWITCH", ValueKind.INT),
        RawEntry("chg_target_soc", 1023, "Setting.SET_DR_SOC_TARGET", ValueKind.INT),
        RawEntry("chg_energy_fb", 1023, "Setting.SET_DR_ENERGY_FB", ValueKind.INT),
        RawEntry("chg_wireless_fitted", 1001, "Charging.CHARGING_HAS_CHARGE_WIRELESS_CHARGING", ValueKind.INT),
        RawEntry("chg_wireless_on", 1001, "Charging.CHARGING_CHARGE_WIRELESS_CHARGING_SWITCH", ValueKind.INT),
        RawEntry("seat_heat_drv", 1000, "Ac.AC_MAIN_DRIVE_SEAT_HEATING_LEVEL", ValueKind.INT),
        RawEntry("seat_heat_pass", 1000, "Ac.AC_PASSENGER_SEAT_HEATING_LEVEL", ValueKind.INT),
        RawEntry("seat_heat_rl", 1000, "Ac.AC_REAR_LEFT_SEAT_HEATING_LEVEL", ValueKind.INT),
        RawEntry("seat_heat_rr", 1000, "Ac.AC_REAR_RIGHT_SEAT_HEATING_LEVEL", ValueKind.INT),
        RawEntry("seat_vent_drv", 1000, "Ac.AC_MAIN_DRIVE_SEAT_VENTILATING_LEVEL", ValueKind.INT),
        RawEntry("seat_vent_pass", 1000, "Ac.AC_PASSENGER_SEAT_VENTILATING_LEVEL", ValueKind.INT),
        RawEntry("seat_vent_rl", 1000, "Ac.AC_REAR_LEFT_SEAT_VENTILATING_LEVEL", ValueKind.INT),
        RawEntry("seat_vent_rr", 1000, "Ac.AC_REAR_RIGHT_SEAT_VENTILATING_LEVEL", ValueKind.INT),
        RawEntry("belt_main", 1001, "Safety.SAFETY_BELT_COMMAND_AREA_MAIN", ValueKind.INT),
        RawEntry("belt_deputy", 1001, "Safety.SAFETY_BELT_COMMAND_AREA_DEPUTY", ValueKind.INT),
        RawEntry("belt_row_l", 1023, "Setting.SETTING_LEFT_REAR_ROW_SAFETYBELT_STATUS", ValueKind.INT),
        RawEntry("belt_row_mid", 1023, "Setting.SETTING_CENTER_REAR_ROW_SAFETYBELT_STATUS", ValueKind.INT),
        RawEntry("belt_row_r", 1001, "Safety.SAFETY_BELT_COMMAND_AREA_SECOND_ROW_SEAT_RIGHT", ValueKind.INT),
        RawEntry("atmos_color", 1023, "Setting.SET_IAL_FRONT_COLOR", ValueKind.INT),
        RawEntry("atmos_bright", 1023, "Setting.SET_IAL_FRONT_BRIGHTNESS", ValueKind.INT),
        RawEntry("atmos_front_color", 1023, "Setting.SET_IAL_FRONT_COLOR", ValueKind.INT),
        RawEntry("atmos_front_bright", 1023, "Setting.SET_IAL_FRONT_BRIGHTNESS", ValueKind.INT),
        RawEntry("atmos_back_color", 1023, "Setting.SET_IAL_BACK_COLOR", ValueKind.INT),
        RawEntry("atmos_back_bright", 1023, "Setting.SET_IAL_BACK_BRIGHTNESS", ValueKind.INT),
        RawEntry("massage_drv_mode", 1023, "Setting.SET_FRONT_LEFT_SEAT_MASSAGE_MODE", ValueKind.INT),
        RawEntry("massage_drv_level", 1023, "Setting.SET_FRONT_LEFT_SEAT_MASSAGE_LEVEL", ValueKind.INT),
        RawEntry("massage_co_mode", 1023, "Setting.SET_FRONT_RIGHT_SEAT_MASSAGE_MODE", ValueKind.INT),
        RawEntry("massage_co_level", 1023, "Setting.SET_FRONT_RIGHT_SEAT_MASSAGE_LEVEL", ValueKind.INT),
        RawEntry("wiper_f_level", 1001, "Wiper.WIPER_FRONT_WIPER_LEVEL", ValueKind.INT),
        RawEntry("wiper_f_state", 1001, "Wiper.WIPER_AREA_FRONT_STATE", ValueKind.INT),
        RawEntry("wiper_r_state", 1001, "Wiper.WIPER_AREA_REAR_STATE", ValueKind.INT),
        RawEntry("wiper_relay", 1001, "Wiper.WIPER_RELAY_STATE", ValueKind.INT),
        RawEntry("wiper_f_maint", 1023, "Setting.SET_FRONT_WINDSCREEN_WIPER_OVERHAUL_STATE", ValueKind.INT),
        RawEntry("wiper_r_maint", 1023, "Setting.SET_REAR_WINDSCREEN_WIPER_OVERHAUL_STATE", ValueKind.INT),
        RawEntry("inside_light_door", 1023, "Setting.SET_INSIDE_LIGHT_DOOR_STATE", ValueKind.INT),
        RawEntry("inside_light", 1023, "Setting.SET_INSIDE_LIGHT_STATE", ValueKind.INT),
        RawEntry("sensor_temp", 1000, "Sensor.SENSOR_TEMPERATURE", ValueKind.INT),
        RawEntry("sensor_humidity", 1000, "Sensor.SENSOR_HUMIDITY", ValueKind.DOUBLE),
        RawEntry("sensor_light", 1000, "Sensor.SENSOR_LIGHT", ValueKind.INT),
        RawEntry("sensor_slope", 1001, "Sensor.SENSOR_AUTO_SLOPE", ValueKind.INT),
        RawEntry("pm25_in", 1000, "Pm2p5.PM2P5_VALUE_IN", ValueKind.INT),
        RawEntry("pm25_out", 1000, "Pm2p5.PM2P5_VALUE_OUT", ValueKind.INT),
        RawEntry("pm25_online", 1000, "Pm2p5.PM2P5_ONLINE_STATE", ValueKind.INT),
        RawEntry("engine_rpm", 1001, "Engine.ENGINE_SPEED", ValueKind.INT),
        RawEntry("engine_rpm_gb", 1001, "Engine.ENGINE_SPEED_GB", ValueKind.INT),
        RawEntry("engine_power", 1001, "Engine.ENGINE_POWER", ValueKind.INT),
        RawEntry("engine_disp", 1001, "Engine.ENGINE_DISPLACEMENT", ValueKind.INT),
        RawEntry("motor_f_rpm", 1001, "Engine.ENGINE_FRONT_MOTOR_SPEED", ValueKind.INT),
        RawEntry("motor_r_rpm", 1001, "Engine.ENGINE_REAR_MOTOR_SPEED", ValueKind.INT),
        RawEntry("motor_f_torque", 1001, "Engine.ENGINE_FRONT_MOTOR_TORQUE", ValueKind.INT),
        RawEntry("motor_r_torque", 1001, "Engine.ENGINE_REAR_MOTOR_TORQUE_F", ValueKind.INT),
        RawEntry("voice_sim", 1001, "Engine.ENGINE_VOICE_SIMULATOR_STATE", ValueKind.INT),
        RawEntry("voice_sim_source", 1001, "Engine.ENGINE_SIMULATOR_SOURCE_TYPE", ValueKind.INT),
        RawEntry("gearbox_type", 1001, "Gearbox.GEARBOX_TYPE", ValueKind.INT),
        RawEntry("gearbox_auto_mode", 1001, "Gearbox.GEARBOX_AUTO_MODE_TYPE", ValueKind.INT),
        RawEntry("gear_manual", 1001, "Gearbox.GEARBOX_MANUAL_MODE_LEVEL", ValueKind.INT),
        RawEntry("epb_state", 1001, "Gearbox.GEARBOX_EPB_STATE", ValueKind.INT),
        RawEntry("park_brake", 1001, "Gearbox.GEARBOX_PARK_BRAKE_SWITCH", ValueKind.INT),
        RawEntry("energy_state", 1001, "Energy.ENERGY_STATE", ValueKind.INT),
        RawEntry("regen_power", 1001, "Energy.ENERGY_POWER_GENERATION_VALUE", ValueKind.INT),
        RawEntry("accelerator_pct", 1001, "Speed.SPEED_ACCELERATOR_S", ValueKind.INT),
        RawEntry("brake_pct", 1001, "Speed.SPEED_BRAKE_S", ValueKind.INT),
        RawEntry("cruise_set_speed", 1001, "Speed.SPEED_AUTO_SPEED", ValueKind.INT),
        RawEntry("avh_state", 1001, "Adas.ADAS_AVH_STATE", ValueKind.INT),
        RawEntry("stat_total_km", 1001, "Statistic.STATISTIC_TOTAL_MILEAGE", ValueKind.INT),
        RawEntry("stat_ev_km", 1001, "Statistic.STATISTIC_MILEAGE_EV", ValueKind.INT),
        RawEntry("stat_hev_km", 1001, "Statistic.STATISTIC_MILEAGE_HEV", ValueKind.INT),
        RawEntry("stat_total_elec_kwh", 1001, "Statistic.STATISTIC_TOTAL_ELEC_CONSUMPTION", ValueKind.INT),
        RawEntry("stat_total_fuel_l", 1001, "Statistic.STATISTIC_TOTAL_FUEL_CONSUMPTION", ValueKind.INT),
        RawEntry("stat_total_elec_phm", 1001, "Statistic.STATISTIC_TOTAL_ELEC_CON_PHM", ValueKind.INT),
        RawEntry("stat_total_fuel_phm", 1001, "Statistic.STATISTIC_TOTAL_FUEL_CON_PHM", ValueKind.INT),
        RawEntry("stat_last_elec_phm", 1001, "Statistic.STATISTIC_LAST_ELEC_CON_PHM", ValueKind.INT),
        RawEntry("stat_last_fuel_phm", 1001, "Statistic.STATISTIC_LAST_FUEL_CON_PHM", ValueKind.INT),
        RawEntry("stat_instant_elec", 1001, "Statistic.STATISTIC_INSTANT_EV_CONSUME", ValueKind.INT),
        RawEntry("stat_instant_fuel", 1001, "Statistic.STATISTIC_INSTANT_FUEL_CONSUME", ValueKind.INT),
        RawEntry("stat_battery_health", 1001, "Statistic.STATISTIC_BATTERY_HEALTHY_INDEX", ValueKind.INT),
        RawEntry("stat_battery_avg_temp", 1001, "Statistic.STATISTIC_AVERAGE_BATTERY_TEMP", ValueKind.DOUBLE),
        RawEntry("stat_battery_max_temp", 1001, "Statistic.STATISTIC_HIGHEST_BATTERY_TEMP", ValueKind.DOUBLE),
        RawEntry("stat_battery_min_temp", 1001, "Statistic.STATISTIC_LOWEST_BATTERY_TEMP", ValueKind.DOUBLE),
        RawEntry("stat_battery_max_v", 1001, "Statistic.STATISTIC_HIGHEST_BATTERY_VOLTAGE", ValueKind.INT),
        RawEntry("stat_battery_min_v", 1001, "Statistic.STATISTIC_LOWEST_BATTERY_VOLTAGE", ValueKind.INT),
        RawEntry("water_temp", 1001, "Statistic.STATISTIC_WATER_TEMPERATURE", ValueKind.DOUBLE),
        RawEntry("battery_wh", 1001, "Statistic.STATISTIC_REMAINING_BATTERY_POWER", ValueKind.INT),
        RawEntry("fuel_pct", 1001, "Statistic.STATISTIC_FUEL_PERCENTAGE", ValueKind.INT),
        RawEntry("radar_l", 1001, "Radar.RADAR_OBSTACLE_DISTANCE_LEFT", ValueKind.INT),
        RawEntry("radar_r", 1001, "Radar.RADAR_OBSTACLE_DISTANCE_RIGHT", ValueKind.INT),
        RawEntry("radar_lf", 1001, "Radar.RADAR_OBSTACLE_DISTANCE_LEFT_FRONT", ValueKind.INT),
        RawEntry("radar_rf", 1001, "Radar.RADAR_OBSTACLE_DISTANCE_RIGHT_FRONT", ValueKind.INT),
        RawEntry("radar_lr", 1001, "Radar.RADAR_OBSTACLE_DISTANCE_LEFT_REAR", ValueKind.INT),
        RawEntry("radar_rr", 1001, "Radar.RADAR_OBSTACLE_DISTANCE_RIGHT_REAR", ValueKind.INT),
        RawEntry("radar_flm", 1001, "Radar.RADAR_OBSTACLE_DISTANCE_FRONT_LEFT_MID", ValueKind.INT),
        RawEntry("radar_frm", 1001, "Radar.RADAR_OBSTACLE_DISTANCE_FRONT_RIGHT_MID", ValueKind.INT),
        RawEntry("radar_mr_dist", 1001, "Radar.RADAR_MR_OBSTACLE_DIS", ValueKind.INT),
        RawEntry("radar_mr_state", 1001, "Radar.RADAR_MR_SONDE_STATUS", ValueKind.INT),
        RawEntry("radar_rev_sw", 1001, "Radar.RADAR_REVERSE_RADAR_SWITCH_STATE", ValueKind.INT),
        RawEntry("ac_quick_clean_3da_online", 1000, "Ac.AC_QUICK_CLEAN_AIR_3DA_ONLINE", ValueKind.INT),
        RawEntry("ac_quick_clean_tip", 1000, "Ac.AC_QUICK_CLEAN_AIR_TIP", ValueKind.INT),
        RawEntry("chg_eta_change", 1001, "Charging.CHARGING_FULL_REST_TIME_CHANGE", ValueKind.INT),
        RawEntry("energy_mode_ic", 1001, "Energy.ENERGY_MODE_INSTRUMENT", ValueKind.INT),
        RawEntry("location_change", 1001, "Location.LOCATION_CHANGE", ValueKind.INT),
        RawEntry("ota_batt_v", 1001, "Ota.OTA_BATTERY_VOLTAGE", ValueKind.DOUBLE),
        RawEntry("ota_batt_power_v", 1001, "Ota.OTA_BATTERY_POWER_VOLTAGE", ValueKind.DOUBLE),
        RawEntry("panorama_output", 1001, "Panorama.PANORAMA_OUTPUT_STATE", ValueKind.INT),
        RawEntry("panorama_work", 1001, "Panorama.PANORAMA_WORK_MODE", ValueKind.INT),
        RawEntry("pm25_changed", 1000, "Pm2p5.PM2P5_VALUE_CHANGED", ValueKind.INT),
        RawEntry("radar_probe_l", 1001, "Radar.RADAR_PROBE_STATE_LEFT", ValueKind.INT),
        RawEntry("radar_probe_r", 1001, "Radar.RADAR_PROBE_STATE_RIGHT", ValueKind.INT),
        RawEntry("radar_probe_lf", 1001, "Radar.RADAR_PROBE_STATE_LEFT_FRONT", ValueKind.INT),
        RawEntry("radar_probe_lr", 1001, "Radar.RADAR_PROBE_STATE_LEFT_REAR", ValueKind.INT),
        RawEntry("radar_probe_rr", 1001, "Radar.RADAR_PROBE_STATE_RIGHT_REAR", ValueKind.INT),
        RawEntry("radar_probe_flm", 1001, "Radar.RADAR_PROBE_STATE_FRONT_LEFT_MID", ValueKind.INT),
        RawEntry("radar_probe_frm", 1001, "Radar.RADAR_PROBE_STATE_FRONT_RIGHT_MID", ValueKind.INT),
        RawEntry("belt_pass_deputy", 1001, "Safety.SAFETY_BELT_PASSENGER_COMMAND_DEPUTY", ValueKind.INT),
        RawEntry("belt_pass_row_l", 1001, "Safety.SAFETY_BELT_PASSENGER_COMMAND_SECOND_ROW_SEAT_LEFT", ValueKind.INT),
        RawEntry("belt_pass_row_mid", 1001, "Safety.SAFETY_BELT_PASSENGER_COMMAND_SECOND_ROW_SEAT_MID", ValueKind.INT),
        RawEntry("belt_pass_row_r", 1001, "Safety.SAFETY_BELT_PASSENGER_COMMAND_SECOND_ROW_SEAT_RIGHT", ValueKind.INT),
        RawEntry("stat_elec_pct", 1001, "Statistic.STATISTIC_ELEC_PERCENTAGE", ValueKind.INT),
        RawEntry("tyre_pressure_lf", 1001, "Tyre.TYRE_PRESSURE_VALUE_LEFT_FRONT", ValueKind.DOUBLE),
        RawEntry("tyre_pressure_rf", 1001, "Tyre.TYRE_PRESSURE_VALUE_RIGHT_FRONT", ValueKind.DOUBLE),
        RawEntry("tyre_pressure_lr", 1001, "Tyre.TYRE_PRESSURE_VALUE_LEFT_REAR", ValueKind.DOUBLE),
        RawEntry("tyre_pressure_rr", 1001, "Tyre.TYRE_PRESSURE_VALUE_RIGHT_REAR", ValueKind.DOUBLE),
    )

    /** Resolve every entry against the framework catalog; drop
     *  unresolved names silently (feature absent on this trim).
     *  Built lazily on first access; results cached.  */
    val list: List<StatusKey> by lazy {
        raw.mapNotNull { e ->
            val key = BydAutoFeatureIdsCatalog.resolve(e.featureName) ?: return@mapNotNull null
            when (e.valueKind) {
                ValueKind.DOUBLE -> StatusKey.DoubleKey(label = e.label, dt = e.deviceType, key = key)
                ValueKind.BYTES -> StatusKey.BytesKey(label = e.label, dt = e.deviceType, key = key)
                ValueKind.INT_ARRAY -> StatusKey.IntArrayKey(label = e.label, dt = e.deviceType, key = key)
                ValueKind.INT -> StatusKey.IntKey(label = e.label, dt = e.deviceType, key = key)
            }
        }
    }
}
