/// BYD status-key facet — the Kotlin-only read concerns (device bus +
/// value-decode kind) for each status label, keyed by `_Sig.name`.
///
/// This is **codegen input, not a runtime path**: `StatusKeyCatalog.kt` is
/// GENERATED from this map + `bydStatusLabelToCatalog` (the framework name)
/// via `tool/gen_status_key_catalog.dart`, so the device-type/value-kind
/// data lives in exactly ONE place. Hand-edit when adding a status-read
/// key (then regenerate); a guard test enforces every key here resolves to
/// a `_entries` framework.
library;

/// Read value-decode kind — mirrors the Kotlin `StatusKeyCatalog.ValueKind`.
enum SignalValueKind { intValue, doubleValue, bytes, intArray }

/// label -> (BYD device bus id, value-decode kind). 205 keys.
const Map<String, ({int deviceType, SignalValueKind valueKind})>
bydStatusKeyFacet = {
  'door_lock': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'door_lf': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'door_rf': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'door_lr': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'door_rr': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'trunk': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'ac_power': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'ac_fan': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'ac_wind_mode': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'ac_cycle': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'ac_target_temp': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'ac_cabin_temp': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'ac_temp_out': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'headlight': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'low_beam': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'high_beam': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'front_fog': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'rear_fog': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'battery_pct': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'range_ev_km': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'range_fuel_km': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'ev_mode': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'hev_mode': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'speed_kmh': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'sunroof_state': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'sunroof_position': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'lock_lf': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'lock_rf': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'lock_lr': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'lock_rr': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'lock_back': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'child_lock_l': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'child_lock_r': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'hood': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'fuel_cap': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'window_lf': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'window_rf': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'window_lr': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'window_rr': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'window_lf_pct': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'window_rf_pct': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'window_lr_pct': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'window_rr_pct': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'moon_roof': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'moon_roof_pct': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'sunshade': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'sunshade_pct': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'rain_auto_close': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'ac_ctrl_mode': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'ac_compressor': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'ac_target_temp_co': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'ac_target_temp_rear': (
    deviceType: 1000,
    valueKind: SignalValueKind.intValue,
  ),
  'ac_temp_unit': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'ac_defrost_f': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'ac_defrost_r': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'ac_max_cool': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'ac_vent': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'ac_rear_power': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'ac_temp_separate': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'ac_quick_clean': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'ac_auto_clean': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'turn_left': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'turn_right': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'turn_signal': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'drl': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'foot_light': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'side_light': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'stalk_l': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'stalk_r': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'tpms_pressure_lf': (
    deviceType: 1001,
    valueKind: SignalValueKind.doubleValue,
  ),
  'tpms_pressure_rf': (
    deviceType: 1001,
    valueKind: SignalValueKind.doubleValue,
  ),
  'tpms_pressure_lr': (
    deviceType: 1001,
    valueKind: SignalValueKind.doubleValue,
  ),
  'tpms_pressure_rr': (
    deviceType: 1001,
    valueKind: SignalValueKind.doubleValue,
  ),
  'tpms_temp_lf': (deviceType: 1001, valueKind: SignalValueKind.doubleValue),
  'tpms_temp_rf': (deviceType: 1001, valueKind: SignalValueKind.doubleValue),
  'tpms_temp_lr': (deviceType: 1001, valueKind: SignalValueKind.doubleValue),
  'tpms_temp_rr': (deviceType: 1001, valueKind: SignalValueKind.doubleValue),
  'chg_cap_ac': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'chg_cap_dc': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'chg_capacity': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'chg_power': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'chg_work_state': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'chg_eta_h': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'chg_eta_m': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'chg_soc_save': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'chg_target_soc': (deviceType: 1023, valueKind: SignalValueKind.intValue),
  'chg_energy_fb': (deviceType: 1023, valueKind: SignalValueKind.intValue),
  'chg_wireless_fitted': (
    deviceType: 1001,
    valueKind: SignalValueKind.intValue,
  ),
  'chg_wireless_on': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'seat_heat_drv': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'seat_heat_pass': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'seat_heat_rl': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'seat_heat_rr': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'seat_vent_drv': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'seat_vent_pass': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'seat_vent_rl': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'seat_vent_rr': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'belt_main': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'belt_deputy': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'belt_row_l': (deviceType: 1023, valueKind: SignalValueKind.intValue),
  'belt_row_mid': (deviceType: 1023, valueKind: SignalValueKind.intValue),
  'belt_row_r': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'atmos_color': (deviceType: 1023, valueKind: SignalValueKind.intValue),
  'atmos_bright': (deviceType: 1023, valueKind: SignalValueKind.intValue),
  'atmos_front_color': (deviceType: 1023, valueKind: SignalValueKind.intValue),
  'atmos_front_bright': (deviceType: 1023, valueKind: SignalValueKind.intValue),
  'atmos_back_color': (deviceType: 1023, valueKind: SignalValueKind.intValue),
  'atmos_back_bright': (deviceType: 1023, valueKind: SignalValueKind.intValue),
  'massage_drv_mode': (deviceType: 1023, valueKind: SignalValueKind.intValue),
  'massage_drv_level': (deviceType: 1023, valueKind: SignalValueKind.intValue),
  'massage_co_mode': (deviceType: 1023, valueKind: SignalValueKind.intValue),
  'massage_co_level': (deviceType: 1023, valueKind: SignalValueKind.intValue),
  'wiper_f_level': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'wiper_f_state': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'wiper_r_state': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'wiper_relay': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'wiper_f_maint': (deviceType: 1023, valueKind: SignalValueKind.intValue),
  'wiper_r_maint': (deviceType: 1023, valueKind: SignalValueKind.intValue),
  'inside_light_door': (deviceType: 1023, valueKind: SignalValueKind.intValue),
  'inside_light': (deviceType: 1023, valueKind: SignalValueKind.intValue),
  'sensor_temp': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'sensor_humidity': (deviceType: 1000, valueKind: SignalValueKind.doubleValue),
  'sensor_light': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'sensor_slope': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'pm25_in': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'pm25_out': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'pm25_online': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'engine_rpm': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'engine_rpm_gb': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'engine_power': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'engine_disp': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'motor_f_rpm': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'motor_r_rpm': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'motor_f_torque': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'motor_r_torque': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'voice_sim': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'voice_sim_source': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'gearbox_type': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'gearbox_auto_mode': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'gear_manual': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'epb_state': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'park_brake': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'energy_state': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'regen_power': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'accelerator_pct': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'brake_pct': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'cruise_set_speed': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'avh_state': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'stat_total_km': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'stat_ev_km': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'stat_hev_km': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'stat_total_elec_kwh': (
    deviceType: 1001,
    valueKind: SignalValueKind.intValue,
  ),
  'stat_total_fuel_l': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'stat_total_elec_phm': (
    deviceType: 1001,
    valueKind: SignalValueKind.intValue,
  ),
  'stat_total_fuel_phm': (
    deviceType: 1001,
    valueKind: SignalValueKind.intValue,
  ),
  'stat_last_elec_phm': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'stat_last_fuel_phm': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'stat_instant_elec': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'stat_instant_fuel': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'stat_battery_health': (
    deviceType: 1001,
    valueKind: SignalValueKind.intValue,
  ),
  'stat_battery_avg_temp': (
    deviceType: 1001,
    valueKind: SignalValueKind.doubleValue,
  ),
  'stat_battery_max_temp': (
    deviceType: 1001,
    valueKind: SignalValueKind.doubleValue,
  ),
  'stat_battery_min_temp': (
    deviceType: 1001,
    valueKind: SignalValueKind.doubleValue,
  ),
  'stat_battery_max_v': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'stat_battery_min_v': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'water_temp': (deviceType: 1001, valueKind: SignalValueKind.doubleValue),
  'battery_wh': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'fuel_pct': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'radar_l': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'radar_r': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'radar_lf': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'radar_rf': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'radar_lr': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'radar_rr': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'radar_flm': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'radar_frm': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'radar_mr_dist': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'radar_mr_state': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'radar_rev_sw': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'ac_quick_clean_3da_online': (
    deviceType: 1000,
    valueKind: SignalValueKind.intValue,
  ),
  'ac_quick_clean_tip': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'chg_eta_change': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'energy_mode_ic': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'location_change': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'ota_batt_v': (deviceType: 1001, valueKind: SignalValueKind.doubleValue),
  'ota_batt_power_v': (
    deviceType: 1001,
    valueKind: SignalValueKind.doubleValue,
  ),
  'panorama_output': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'panorama_work': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'pm25_changed': (deviceType: 1000, valueKind: SignalValueKind.intValue),
  'radar_probe_l': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'radar_probe_r': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'radar_probe_lf': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'radar_probe_lr': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'radar_probe_rr': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'radar_probe_flm': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'radar_probe_frm': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'belt_pass_deputy': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'belt_pass_row_l': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'belt_pass_row_mid': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'belt_pass_row_r': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'stat_elec_pct': (deviceType: 1001, valueKind: SignalValueKind.intValue),
  'tyre_pressure_lf': (
    deviceType: 1001,
    valueKind: SignalValueKind.doubleValue,
  ),
  'tyre_pressure_rf': (
    deviceType: 1001,
    valueKind: SignalValueKind.doubleValue,
  ),
  'tyre_pressure_lr': (
    deviceType: 1001,
    valueKind: SignalValueKind.doubleValue,
  ),
  'tyre_pressure_rr': (
    deviceType: 1001,
    valueKind: SignalValueKind.doubleValue,
  ),
};
