import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'package:ilink/kernel/i18n/generated/app_localizations.dart';
import 'package:ilink/kernel/update/models/release_manifest.dart';
import 'package:ilink/app/update/update_controller.dart';
import 'package:ilink/app/update/update_orchestrator.dart';
import 'package:ilink/app/update/update_state.dart';

// Returns a human-readable file size, e.g. "46.1 MB".
String _formatBytes(int bytes) {
  final mb = bytes / (1024 * 1024);
  return '${mb.toStringAsFixed(1)} MB';
}

// Compiled once at file load — `_formatNotes` is called twice per build
// (visibility check + render) and these patterns are otherwise re-compiled
// on every keystroke-equivalent rebuild.
final _kCodeFenceRe = RegExp(r'```[\s\S]*?```', multiLine: true);
final _kHeadingRe = RegExp(r'^#{1,6}\s+', multiLine: true);
final _kMdLinkRe = RegExp(r'\[([^\]]+)\]\([^)]+\)');
final _kBareUrlRe = RegExp(r'https?://\S+');
final _kStarsRe = RegExp(r'\*+');
final _kBulletRe = RegExp(r'^[-*]\s+', multiLine: true);
final _kHrRe = RegExp(r'^---+$', multiLine: true);
final _kBlankRunRe = RegExp(r'\n{3,}');

// Strips CHANGELOG markdown to plain text suitable for the dialog body
// and truncates. The notes are auto-generated by release-please so
// they're full of `## Bug Fixes`, `[text](url)`, version compare links,
// SHA verification snippets, etc. — none of which renders correctly in
// a plain `Text()`. Strip the syntax, keep the bullet text, drop links
// and code fences.
String _formatNotes(String raw) {
  var s = raw;
  s = s.replaceAll(_kCodeFenceRe, '');
  s = s.replaceAll(_kHeadingRe, '');
  s = s.replaceAllMapped(_kMdLinkRe, (m) => m.group(1) ?? '');
  s = s.replaceAll(_kBareUrlRe, '');
  s = s.replaceAll('`', '');
  s = s.replaceAll(_kStarsRe, '');
  s = s.replaceAll(_kBulletRe, '• ');
  s = s.replaceAll(_kHrRe, '');
  s = s.replaceAll(_kBlankRunRe, '\n\n');
  s = s.trim();
  if (s.length > 240) s = '${s.substring(0, 240).trimRight()}…';
  return s;
}

class UpdatePromptDialog extends ConsumerWidget {
  const UpdatePromptDialog({super.key, required this.manifest});

  final ReleaseManifest manifest;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final t = S.of(context);
    final installedCode = ref.watch(installedVersionCodeProvider).value ?? 0;
    final isForced = manifest.requiresForceUpdate(installedCode);

    final updateState = ref.watch(updateControllerProvider).value;
    final isDownloading = updateState is UpdateDownloading;
    final progress = isDownloading ? updateState.progress : null;
    final isInstalling = updateState is UpdateInstalling;
    final isFailed = updateState is UpdateFailed;

    // Force LTR even when the app is in Arabic — version strings,
    // file sizes, and the action button row read more naturally
    // left-to-right; mirroring made the size+version line ("0.0.20-b
    // · 35.3 MB") render with the version on the right and the size
    // on the left, which looked broken.
    return Directionality(
      textDirection: TextDirection.ltr,
      child: AlertDialog(
        title: Text(
          isForced ? t.otaUpdateRequiredTitle : t.otaUpdateAvailableTitle,
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              '${manifest.versionName} · ${_formatBytes(manifest.sizeBytes)}',
            ),
            // Compute once — `_formatNotes` runs the full markdown-strip
            // pipeline; we used to call it twice (visibility + render).
            ...(() {
              final notes = manifest.releaseNotes;
              if (notes == null) return const <Widget>[];
              final stripped = _formatNotes(notes);
              if (stripped.isEmpty) return const <Widget>[];
              return [const SizedBox(height: 8), Text(stripped)];
            }()),
            if (isDownloading) ...[
              const SizedBox(height: 16),
              LinearProgressIndicator(value: progress),
              const SizedBox(height: 4),
              Text('${((progress ?? 0) * 100).toStringAsFixed(0)}%'),
            ],
            if (isFailed) ...[
              const SizedBox(height: 8),
              Text(t.otaDownloadFailed),
            ],
          ],
        ),
        actions: [
          if (!isForced)
            TextButton(
              onPressed: isDownloading || isInstalling
                  ? null
                  : () {
                      ref.read(updateControllerProvider.notifier).defer();
                      ref.read(promptUpdateProvider.notifier).value = null;
                      Navigator.of(context).pop();
                    },
              child: Text(t.otaLater),
            ),
          if (isForced)
            TextButton(
              onPressed: isDownloading || isInstalling
                  ? null
                  : () => SystemNavigator.pop(),
              child: Text(t.otaExitApp),
            ),
          FilledButton(
            onPressed: isDownloading || isInstalling
                ? null
                : () => _onInstall(ref),
            child: Text(t.otaInstallNow),
          ),
        ],
      ),
    );
  }

  Future<void> _onInstall(WidgetRef ref) async {
    final current = ref.read(updateControllerProvider).value;
    if (current is UpdateAvailable) {
      await ref.read(updateControllerProvider.notifier).download();
    } else if (current is UpdateReadyToInstall) {
      await ref.read(updateControllerProvider.notifier).install();
    } else if (current is UpdateFailed) {
      // Retry from the top on a transient failure.
      await ref.read(updateControllerProvider.notifier).check();
    }
  }
}
